console.log(Math.abs(-4));
console.log(Math.PI);
console.log(Math.LN10);
console.log(Math.SQRT2);
console.log(Math.ceil(6.3));
console.log(Math.floor(6.3));
console.log(Math.log10(20));
console.log(Math.max(20,11,3421,12));
console.log(Math.random());